default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  encoding: utf8
  reconnect: false
  username: postgres
  password: secret

test:
  <<: *default
  database: test

development:
  <<: *default
  database: development

production:
  <<: *default
  database: production